### PR TITLE
Desktop app automation and development roundtrip

### PR DESCRIPTION
**Pull request by athiele**
As I don't know how you package the apps for windows / linux, I just added the darwin packaging. You should add the electron-package commands you use for the other platforms.

### CODE REVIEW

**Comment by wwebfor** [comment]
First of all, thank you for the PR.

We use Gulp tasks to build a desktop app. We changed the task a little to make it possible to specify a platform:

```bash
gulp electron darwin-x64
```

Probably it isn't necessary to have `electron-prebuilt` in dependencies since the Gulp task downloads and caches it anyway.

**Comment by athiele** [comment]
Alright - good solution. What is the gulp way of starting the electron app quickly for development?

**Comment by wwebfor** [comment]
We just use `electron electron.js` :)

**Comment by athiele** [comment]
OK, anyway I will close this PR as you incorporated some of the suggestions already.

**Pull request closed without merging**
