### PR TITLE
Settings: Indent unit

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by claell** [comment]
I guess this is to set a custom amount of spaces that will be indented?

You mentioned in #594 that 3 spaces are needed in order to make lists indent properly. To avoid irritation it would probably good to either
- Output a warning or something else when setting unit to a value below 3
- Allow lists to indent properly for values below 3

**Comment by talklittle** [comment]
Good suggestion, added a warning when setting to value below 3. And changed default to 3.

**Comment by claell** [comment]
I think I'd rather prefer 4 as default like it was (maybe since it is an even number). I think it is also more widely used in other editors, but did not research much, so correct me if I am wrong.

**Comment by talklittle** [comment]
I suspect you're right. Reverted default to 4.

**Comment by claell** [comment]
Alright :+1:

**Comment by wwebfor** [comment]
Thanks for the PR ;)

**Pull request merged**
