### PR TITLE
Handle empty title

### LINKED ISSUE #540: Trying to save a note with no title silently fails
If you create a new note and do not enter a title, saving the note silently fails. This should (imo) either display an error message or just apply an auto-generated note title.

I really appreciate this project so I would like to contribute some code to it. I started to poke around in the codebase a bit and came up with a somehow decent solution (going for the auto-generated title approach), which you can review here if you want to: https://github.com/janis-kra/laverna/commit/5e09bb7355938bc19f42e43c0a96b66cf78057a6

I'll open a pull request if you think that this could be at least the basis for a solution for this issue.

### PR DESCRIPTION
**Pull request by janis-kra**
When saving a note, check if the title is empty and, if yes, give it a default name ('New Note').

Fixes #540

### CODE REVIEW

**Comment by NWuensche** [comment]
I would also like Untitled more than New Note.

**Comment by claell** [comment]
What happens, if a user creates several notes without a name? Will there be several notes with the name "Untitled"? Is it a problem, when some notes have the same name?

**Comment by janis-kra** [comment]
@claell yes this can happen, but it seems that this is not a problem: 

screen shot 2016-08-12 at 21 54 37

**Comment by claell** [comment]
Alright

**Pull request merged**
