### PR TITLE
Fehler beseitigt die beim ersten Aufruf erscheinen

### PR DESCRIPTION
**Pull request by Erfahrungen**
Der Import Button ist nicht gelb und der 'Weiter' Button heißt 'Nächste'.

### CODE REVIEW

**Comment by NWuensche** [comment]
Nur als Vorschlag: Wäre es nicht besser, den Button "Weiter" zu nennen? Ich persönlich finde, dass das besser klingt als "Nächste". Trotzdem ein berechtigter PR.

**Comment by claell** [comment]
I think we should keep this conversation in English. I also prefer "Weiter", seems to be Standard for most programs.

**Comment by wwebfor** [comment]
I don't know German at al. So it is up to you guys who speak German to decide if it should be merged.

**Comment by NWuensche** [comment]
Sorry for writing German. Of course it is better if we write in English. I would say that you shouldn't merge it write now, because the message should be changed from "Nächster" to "Weiter".

**Comment by Erfahrungen** [comment]
This should be fixed with a high priority, since users get wrong information in the very first screen.

**Comment by claell** [comment]
Ah I think I misunderstood your changes. But for the button I'd prefer to change it's naming and not the description.

**Comment by Erfahrungen** [comment]
I'm new to this. Who can merge this now?

**Comment by claell** [comment]
The last changes are looking good.
The repo owners can do merging.

**Comment by wwebfor** [comment]
@Erfahrungen thanks for the pull request :)

**Pull request merged**
